#ifndef IMAGES_IDS_H
#define IMAGES_IDS_H

#define NULL_IMAGE 0

// HUD
#define HUD_BACKGROUND 100
#define HUD_BJ_FACES 101
#define HUD_NUMBER 102
#define HUD_KEY 103
#define HUD_KNIFE 104
#define HUD_PISTOL 105
#define HUD_CHAINCANNON 106
#define HUD_MACHINEGUN 107
#define HUD_ROCKETLAUNCHER 108
#define HUD_DEATH_TEXT 109

// LEADERBOARD
#define LB_BACKGROUND 200

#endif