#ifndef IMAGES_IDS_H
#define IMAGES_IDS_H

#define NULL_IMAGE 0

#define PREFEER_WIDTH 320
#define PREFEER_HEIGHT 200
#define PIXEL 1

#define NUMBER_FRAME_X_COUNT 10
#define FACE_FRAME_X_COUNT 3
#define FACE_FRAME_Y_COUNT 7

#define GREEN_NUMBERS 90

// HUD
#define HUD_BACKGROUND 100
#define HUD_BJ_FACES 101
#define HUD_NUMBER 102
#define HUD_KEY 103
#define HUD_KNIFE 104
#define HUD_PISTOL 105
#define HUD_CHAINCANNON 106
#define HUD_MACHINEGUN 107
#define HUD_ROCKETLAUNCHER 108
#define HUD_DEATH_TEXT 109
#define HUD_KNIFE_SHOOT 110
#define HUD_PISTOL_SHOOT 111
#define HUD_CHAINCANNON_SHOOT 112
#define HUD_MACHINEGUN_SHOOT 113
#define HUD_ROCKETLAUNCHER_SHOOT 114

// LEADERBOARD
#define LB_BACKGROUND 200
#define LB_BOTTOM_BANNER 201
#define LB_TOP_BANNER 202
#define LB_VICTORY 203
#define LB_DEFEAT 204

#endif